name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
      working-directory: ./common
    - run: npm test
      working-directory: ./common      
    - run: npm publish
      working-directory: ./common
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Wait for NPM
      run: sleep 15
    - run: npm install
      working-directory: ./backend
    - run: npm publish
      working-directory: ./backend
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: npm install
      working-directory: ./frontend
    - run: npm publish
      working-directory: ./frontend
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Wait for NPM
      run: sleep 15
    - name: Install Packages
      run: npm install
      working-directory: ./docs
    - name: Build page
      run: CI=false npm run build
      working-directory: ./docs
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs/build
